#!/usr/bin/env python3
"""Build the confirmed species, cosmetic, gameplay-data and demo-status layer."""

from html import escape
from pathlib import Path
import json
import re

ROOT=Path(__file__).resolve().parents[1]
SITE='https://starwarszerocompany.cc'
TODAY='2026-07-19'
ADS_META='<meta name="google-adsense-account" content="ca-pub-9505220977121599">'
ADS_SCRIPT='<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9505220977121599" crossorigin="anonymous"></script>'
PRESS='https://news.ea.com/press-releases/press-releases-details/2026/Command-the-Clone-Wars-Most-Cunning-Operatives-in-Star-Wars-Zero-Company-Launching-August-27/default.aspx'
GAMEPLAY='https://www.ea.com/games/starwars/zero-company/news/lead-zero-company-to-victory'
BUY='https://www.ea.com/games/starwars/zero-company/buy'
PREORDER='https://help.ea.com/en/articles/star-wars/zero-company/pre-order-guide/'
STEAM='https://store.steampowered.com/app/2075800/STAR_WARS_Zero_Company/'

STYLE=""":root{--bg:#071016;--panel:#0d1922;--panel2:#101f2a;--line:#284050;--text:#edf7ff;--muted:#a8bac5;--teal:#36e0ce;--gold:#e9b84a;--max:1080px}*{box-sizing:border-box}body{margin:0;background:#071016;color:var(--text);font:16px/1.72 system-ui,-apple-system,Segoe UI,sans-serif}a{color:var(--teal);text-decoration:none}a:hover{text-decoration:underline}.wrap{max-width:var(--max);margin:auto;padding:0 22px}.top{border-bottom:1px solid var(--line);background:#071016f2;position:sticky;top:0;z-index:5}.top .wrap{min-height:62px;display:flex;align-items:center;gap:16px;flex-wrap:wrap}.brand{font-weight:900;color:var(--text)}nav{margin-left:auto;display:flex;gap:14px;flex-wrap:wrap}nav a{color:var(--muted);font-size:14px}.hero{padding:50px 0 28px;border-bottom:1px solid var(--line)}.crumb,.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.14em;color:var(--teal)}h1{font-size:clamp(34px,6vw,56px);line-height:1.08;margin:13px 0}h2{font-size:23px;margin:34px 0 13px;border-left:4px solid var(--teal);padding-left:12px}.lead{font-size:19px;color:#cad8e0;max-width:850px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:15px}.card,.block{display:block;border:1px solid var(--line);border-radius:8px;background:linear-gradient(180deg,var(--panel),var(--panel2));padding:20px;margin:15px 0;color:var(--text)}.status{border-color:rgba(54,224,206,.5)}.note{border-color:rgba(233,184,74,.45)}.pill{display:inline-block;border:1px solid #3d625f;border-radius:4px;padding:5px 9px;color:var(--teal);font-size:12px}.muted,.source{color:var(--muted);font-size:14px}table{width:100%;border-collapse:collapse}th,td{border:1px solid var(--line);padding:11px;text-align:left;vertical-align:top}th{color:var(--gold)}li{margin:8px 0}footer{border-top:1px solid var(--line);margin-top:48px;padding:28px 0;color:var(--muted);font-size:14px}@media(max-width:760px){nav{margin-left:0}.top .wrap{padding-top:10px;padding-bottom:10px}}"""

SPECIES=['Devaronian','Human','Neimoidian','Ovissian','Togruta',"Twi'lek",'Weequay','Zabrak']

# slug, title, type, acquisition, contents/answer
COSMETICS=[
('crystalline-astromech-pack','Crystalline Astromech Cosmetic Pack','Preorder cosmetic pack','Preorder either edition','Unlocks R3 plus crystalline astromech heads for R4, R5 and BR-1.'),
('r3-droid','R3 Droid','Astromech unlock','Crystalline Astromech preorder pack','R3 is the droid unlock explicitly included with the preorder bonus.'),
('br-1-droid','BR-1 Droid','Zero Company astromech','Crystalline Astromech preorder pack','BR-1 is an astromech originating in Star Wars Zero Company and receives a crystalline head option.'),
('r4-r5-crystalline-heads','R4 and R5 Crystalline Astromech Heads','Astromech head cosmetics','Crystalline Astromech preorder pack','Adds translucent crystalline head cosmetics for the R4 and R5 variants.'),
('grand-army-republic-pack','Grand Army of the Republic Cosmetic Pack','Deluxe cosmetic pack','Deluxe Edition','Contains the Republic Officer Uniform, 100th Clone Company Armor Set and ARC Trooper Armor Set.'),
('republic-officer-uniform','Republic Officer Uniform','Outfit cosmetic','Grand Army of the Republic pack in the Deluxe Edition','A Republic-themed uniform cosmetic for squad customization.'),
('100th-clone-company-armor','100th Clone Company Armor Set','Armor cosmetic','Grand Army of the Republic pack in the Deluxe Edition','A Clone Company-inspired armor appearance; no gameplay statistic is advertised.'),
('arc-trooper-armor','ARC Trooper Armor Set','Armor cosmetic','Grand Army of the Republic pack in the Deluxe Edition','An ARC Trooper-inspired armor appearance included with the Deluxe Edition.'),
('shadow-collective-pack','Shadow Collective Cosmetic Pack','Deluxe cosmetic pack','Deluxe Edition','Contains a Pyke helmet and five faction-inspired tattoo cosmetics.'),
('pyke-helmet','Pyke Helmet Cosmetic','Helmet cosmetic','Shadow Collective pack in the Deluxe Edition','A Pyke-styled helmet appearance for character customization.'),
('shadow-collective-tattoos','Five Shadow Collective Tattoo Cosmetics','Tattoo cosmetic set','Shadow Collective pack in the Deluxe Edition','Includes Pyke Syndicate, Hutt Cartel, Death Watch, Black Sun Syndicate and Crimson Dawn tattoos.'),
('painted-weapon-themes','Five Painted Weapon Themes','Weapon appearance collection','Deluxe Edition','Five cosmetic weapon sets change weapon appearance without an advertised combat bonus.'),
('100th-clone-weapon-theme','100th Clone Company Weapon Theme','Painted weapon cosmetic','Deluxe Edition','One of the five Deluxe painted weapon themes.'),
('kafrene-informant-weapon-theme','Kafrene Informant Weapon Theme','Painted weapon cosmetic','Deluxe Edition','One of the five Deluxe painted weapon themes, named for a Kafrene informant.'),
('black-sun-enforcer-weapon-theme','Black Sun Syndicate Enforcer Weapon Theme','Painted weapon cosmetic','Deluxe Edition','One of the five Deluxe painted weapon themes.'),
('bespin-security-weapon-theme','Bespin Security Weapon Theme','Painted weapon cosmetic','Deluxe Edition','One of the five Deluxe painted weapon themes.'),
('separatist-warrior-weapon-theme','Separatist Warrior Weapon Theme','Painted weapon cosmetic','Deluxe Edition','One of the five Deluxe painted weapon themes.'),
]

def chrome(route,title,desc,body,schema_type='Article'):
 schema={"@context":"https://schema.org","@type":schema_type,"headline":title,"description":desc,"url":SITE+route,"dateModified":TODAY,"inLanguage":"en","isPartOf":{"@type":"WebSite","name":"Star Wars Zero Company Wiki","url":SITE+'/'}}
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Star Wars Zero Company Wiki</title><meta name="description" content="{escape(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="{SITE}{route}"><meta property="og:type" content="article"><meta property="og:url" content="{SITE}{route}"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:image" content="{SITE}/assets/zero-company-hero.png"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><style>{STYLE}</style>{ADS_META}{ADS_SCRIPT}</head><body><header class="top"><div class="wrap"><a class="brand" href="/">Star Wars Zero Company Wiki</a><nav><a href="/database/">Database</a><a href="/species/">Species</a><a href="/cosmetics/">Cosmetics</a><a href="/features/">Features</a><a href="/questions/">FAQ</a><a href="/news/">News</a></nav></div></header><main class="wrap">{body}</main><footer><div class="wrap">Unofficial, source-linked database. <a href="/about/sources-and-citations.html">Sources policy</a> · <a href="/sitemap.xml">Sitemap</a></div></footer></body></html>'''

def write(route,title,desc,body,schema_type='Article'):
 p=(ROOT/route.strip('/')/'index.html') if route.endswith('/') else (ROOT/route.lstrip('/'))
 p.parent.mkdir(parents=True,exist_ok=True); p.write_text(chrome(route,title,desc,body,schema_type),encoding='utf-8')

def build_species():
 cards=[]
 for name in SPECIES:
  slug=name.lower().replace("'",'').replace(' ','-')
  title=f'{name} Custom Operator Status'
  desc=f'{name} is one of eight species confirmed for Hawks and recruited custom Operators in Star Wars Zero Company.'
  others=', '.join(x for x in SPECIES if x!=name)
  body=f'''<section class="hero"><div class="crumb"><a href="/database/">Database</a> / <a href="/species/">Species</a></div><span class="pill">Officially confirmed</span><h1>Can You Create a {escape(name)} Operator?</h1><p class="lead"><strong>Yes. {escape(name)} is one of the eight species EA lists for Hawks and recruited Operators.</strong></p></section><section class="block status"><h2>Confirmed Status</h2><table><tr><th>Species</th><td>{escape(name)}</td></tr><tr><th>Available for</th><td>Hawks and recruited custom Operators</td></tr><tr><th>Customization</th><td>Voice, outfit, appearance, Specialization and Talents are described as customizable over time</td></tr></table></section><section class="block"><h2>What the Announcement Establishes</h2><p>EA's June 2026 press release explicitly includes {escape(name)} in the character-creation species list. The other confirmed choices are {escape(others)}.</p><p>The announcement establishes availability as a creation option. It does not assign a species-exclusive combat bonus, fixed Specialization or unique stat line, so those details should not be inferred before launch.</p></section><section class="block note"><h2>Launch Verification</h2><p>The final creator presets, body options, voice combinations, outfit compatibility and any species-specific presentation details will be checked against the August 27 release build. This page will separate cosmetic creator choices from gameplay effects if the shipped game exposes both.</p><p class="source"><a href="{PRESS}" rel="nofollow">EA press release: customization and eight species</a> · Checked July 19, 2026</p></section><section><h2>Related Database Pages</h2><div class="grid"><a class="card" href="/species/"><strong>All 8 Species</strong><br><span class="muted">Compare every confirmed creator option</span></a><a class="card" href="/questions/can-you-create-custom-operators.html"><strong>Can you create custom Operators?</strong><br><span class="muted">Verified FAQ</span></a><a class="card" href="/classes/"><strong>Eight Specializations</strong><br><span class="muted">Combat roles available to most Operators</span></a></div></section>'''
  write(f'/species/{slug}.html',title,desc,body)
  cards.append(f'<a class="card" href="/species/{slug}.html"><strong>{escape(name)}</strong><br><span class="muted">Confirmed custom Operator species</span></a>')
 body=f'''<section class="hero"><div class="crumb"><a href="/database/">Database</a> / Species</div><h1>Custom Operator Species</h1><p class="lead">EA has confirmed eight species for Hawks and recruited Operators: Devaronian, Human, Neimoidian, Ovissian, Togruta, Twi'lek, Weequay and Zabrak.</p></section><section class="block"><h2>Confirmed Creator Data</h2><p>The June 2026 press release connects these species with customizable voices, outfits, appearances, Specializations and Talents. It does not publish racial bonuses or species-locked roles.</p></section><section><h2>All Eight Choices</h2><div class="grid">{''.join(cards)}</div></section><section class="block"><h2>Source</h2><p class="source"><a href="{PRESS}" rel="nofollow">EA press release</a> · Checked July 19, 2026</p></section>'''
 write('/species/','All 8 Custom Operator Species','The complete official list of eight species available for Hawks and custom Operators.',body,'CollectionPage')

def build_cosmetics():
 cards=[]
 for slug,title,kind,acquisition,answer in COSMETICS:
  desc=f'{title} acquisition and contents in Star Wars Zero Company: {answer}'
  body=f'''<section class="hero"><div class="crumb"><a href="/database/">Database</a> / <a href="/cosmetics/">Cosmetics</a></div><span class="pill">Official store data</span><h1>{escape(title)}</h1><p class="lead">{escape(answer)}</p></section><section class="block status"><h2>Item Data</h2><table><tr><th>Name</th><td>{escape(title)}</td></tr><tr><th>Type</th><td>{escape(kind)}</td></tr><tr><th>How to obtain</th><td>{escape(acquisition)}</td></tr><tr><th>Availability</th><td>Available in game at launch for eligible purchases</td></tr></table></section><section class="block"><h2>What Is Included</h2><p>{escape(answer)} EA and its support guide categorize this content as cosmetic. No damage increase, exclusive combat ability or campaign mission is advertised as part of this item.</p><p>That distinction matters for edition comparisons: this entry records appearance content and acquisition, not a power advantage. Regional store wording and prices can vary while the named contents remain the useful comparison point.</p></section><section class="block note"><h2>Current Status and Verification</h2><p>The item is listed in the current preorder or Deluxe Edition material. It becomes usable when Star Wars Zero Company launches on August 27, 2026 for an account that meets the relevant purchase condition.</p><p>In-game menu location, compatible body types, recolor controls and final preview options will be added only after launch testing.</p><p class="source"><a href="{PREORDER}" rel="nofollow">EA Help preorder and edition guide</a> · <a href="{STEAM}" rel="nofollow">Steam edition listing</a> · Checked July 19, 2026</p></section><section><h2>Related Pages</h2><div class="grid"><a class="card" href="/cosmetics/"><strong>Cosmetics Database</strong><br><span class="muted">All confirmed preorder and Deluxe items</span></a><a class="card" href="/official/deluxe-edition.html"><strong>Deluxe Edition</strong><br><span class="muted">Edition comparison</span></a><a class="card" href="/questions/what-is-the-preorder-bonus.html"><strong>Preorder Bonus FAQ</strong><br><span class="muted">Quick verified answer</span></a></div></section>'''
  write(f'/cosmetics/{slug}.html',title,desc,body)
  cards.append(f'<a class="card" href="/cosmetics/{slug}.html"><strong>{escape(title)}</strong><br><span class="muted">{escape(kind)} · {escape(acquisition)}</span></a>')
 body=f'''<section class="hero"><div class="crumb"><a href="/database/">Database</a> / Cosmetics</div><h1>Preorder and Deluxe Cosmetics Database</h1><p class="lead">Confirmed droids, armor, uniforms, helmets, tattoos and weapon themes from the current official edition listings.</p></section><section class="block"><h2>Quick Counts</h2><table><tr><th>Group</th><th>Confirmed contents</th></tr><tr><td>Crystalline Astromech pack</td><td>R3 unlock plus crystalline heads for R4, R5 and BR-1</td></tr><tr><td>Grand Army of the Republic pack</td><td>3 uniform or armor cosmetics</td></tr><tr><td>Shadow Collective pack</td><td>1 helmet and 5 tattoos</td></tr><tr><td>Painted weapon themes</td><td>5 cosmetic weapon sets</td></tr></table></section><section><h2>All Confirmed Entries</h2><div class="grid">{''.join(cards)}</div></section><section class="block"><h2>Source and Scope</h2><p>All entries come from EA's current purchase and support pages or the Steam edition listing. They are cosmetics, not a fabricated item-stat database.</p><p class="source"><a href="{PREORDER}" rel="nofollow">EA Help edition guide</a> · Checked July 19, 2026</p></section>'''
 write('/cosmetics/','Zero Company Cosmetics Database','All confirmed preorder and Deluxe cosmetic items, packs, droids, armor, tattoos and weapon themes.',body,'CollectionPage')

def build_database():
 body=f'''<section class="hero"><div class="crumb">Database / Latest Confirmed Data</div><h1>Latest Confirmed Game Data</h1><p class="lead">A dated snapshot of the official entity counts and launch facts available before release.</p></section><section class="block"><h2>Data Snapshot — July 19, 2026</h2><table><tr><th>Dataset</th><th>Confirmed count or status</th><th>Browse</th></tr><tr><td>Profiled authored Operators</td><td>7</td><td><a href="/operatives/">Operatives</a></td></tr><tr><td>Standard Specializations</td><td>8</td><td><a href="/classes/">Specializations</a></td></tr><tr><td>Custom creator species</td><td>8</td><td><a href="/species/">Species</a></td></tr><tr><td>The Den functions</td><td>9</td><td><a href="/facilities/">Facilities</a></td></tr><tr><td>Deluxe armor/uniform cosmetics</td><td>3</td><td><a href="/cosmetics/">Cosmetics</a></td></tr><tr><td>Shadow Collective tattoos</td><td>5</td><td><a href="/cosmetics/shadow-collective-tattoos.html">Tattoo set</a></td></tr><tr><td>Painted weapon themes</td><td>5</td><td><a href="/cosmetics/painted-weapon-themes.html">Weapon themes</a></td></tr><tr><td>Supported text languages</td><td>11</td><td><a href="/official/languages.html">Languages</a></td></tr><tr><td>Public Demo</td><td>No official listing as of this check</td><td><a href="/features/demo-status.html">Demo status</a></td></tr></table></section><section class="block note"><h2>Quality Boundary</h2><p>This page counts only data explicitly present in current first-party announcements and stores. It deliberately excludes guessed skills, unrevealed equipment, trailer-only stat estimates and unannounced characters.</p></section><section class="grid"><a class="card" href="/database/gameplay-systems.html"><strong>Gameplay Systems Snapshot</strong><br><span class="muted">3 AP, 10 Advantage, 3 Injuries and mission Cycles</span></a><a class="card" href="/species/"><strong>Species Database</strong><br><span class="muted">Eight character creator options</span></a><a class="card" href="/cosmetics/"><strong>Cosmetics Database</strong><br><span class="muted">Preorder and Deluxe contents</span></a><a class="card" href="/features/"><strong>Special Features</strong><br><span class="muted">Campaign systems and Demo status</span></a></section>'''
 write('/database/','Star Wars Zero Company Game Database','Latest confirmed Star Wars Zero Company data for Operators, species, cosmetics, systems and Demo status.',body,'CollectionPage')
 systems=f'''<section class="hero"><div class="crumb"><a href="/database/">Database</a> / Gameplay</div><h1>Confirmed Gameplay Systems Snapshot</h1><p class="lead">The current official numbers and named campaign systems in one compact reference.</p></section><section class="block"><h2>Confirmed Mechanics</h2><table><tr><th>System</th><th>Official fact</th></tr><tr><td>Action economy</td><td>3 AP per Operator per turn</td></tr><tr><td>Advantage</td><td>Shared squad resource with a maximum of 10</td></tr><tr><td>Standard Specialization kit</td><td>1 Ultimate, 1 Standard Ability and 1 Passive</td></tr><tr><td>Injuries</td><td>Third Injury causes permanent death on standard difficulty</td></tr><tr><td>Missions</td><td>HoloTable opportunities advance in Cycles</td></tr><tr><td>Maps</td><td>Handcrafted layouts with randomized enemy and objective elements</td></tr><tr><td>Relationships</td><td>Bonds grow through deployment and unlock combat synergies</td></tr></table></section><section class="block"><h2>What Remains for Launch</h2><p>Exact ability names, AP costs for every action, full weapon statistics, mission rewards, difficulty modifiers and balance values are not published as a complete dataset. Those fields will be populated from the shipped game rather than inferred from trailer frames.</p><p class="source"><a href="{GAMEPLAY}" rel="nofollow">EA gameplay overview</a> · Checked July 19, 2026</p></section><section class="grid"><a class="card" href="/official-systems/"><strong>Official Systems Guides</strong></a><a class="card" href="/questions/"><strong>50 Verified FAQs</strong></a><a class="card" href="/planner/"><strong>Campaign Planners</strong></a></section>'''
 write('/database/gameplay-systems.html','Confirmed Gameplay Systems Data','Official gameplay numbers and systems: AP, Advantage, Injuries, mission Cycles, maps and bonds.',systems)

def build_features():
 demo=f'''<section class="hero"><div class="crumb"><a href="/database/">Database</a> / <a href="/features/">Features</a></div><span class="pill">Status checked July 19, 2026</span><h1>Does Star Wars Zero Company Have a Demo?</h1><p class="lead"><strong>No public Demo is currently announced or listed on the official EA and Steam pages.</strong></p></section><section class="block status"><h2>Current Demo Status</h2><table><tr><th>EA game page</th><td>No Demo download or Demo date listed</td></tr><tr><th>Steam</th><td>Pre-purchase page is live; no Demo button or Demo package is presented</td></tr><tr><th>Release</th><td>Full game launches August 27, 2026</td></tr></table></section><section class="block"><h2>What This Answer Means</h2><p>The absence of a listing is a current-status finding, not proof that EA can never release a trial later. As of the check date, the official calls to action are preorder and wishlist rather than download a Demo.</p><p>Players should avoid unofficial downloads claiming to be a Zero Company Demo. A legitimate public build should be linked from EA or the verified platform storefront.</p></section><section class="block note"><h2>How We Will Track Changes</h2><p>This page will be rechecked when EA publishes a new update, when Steam changes the available packages, and during the final launch week. If a Demo, trial or limited play period appears, the page will add platform, availability window, save-transfer status and official download instructions.</p><p class="source"><a href="{BUY}" rel="nofollow">EA purchase page</a> · <a href="{STEAM}" rel="nofollow">Steam store page</a></p></section><section class="grid"><a class="card" href="/official/release-date.html"><strong>Release Date</strong></a><a class="card" href="/official/platforms.html"><strong>Platforms</strong></a><a class="card" href="/questions/is-zero-company-single-player.html"><strong>Single-Player FAQ</strong></a></section>'''
 write('/features/demo-status.html','Star Wars Zero Company Demo Status','No public Star Wars Zero Company Demo is currently announced or listed. See the dated EA and Steam status check.',demo)
 body='''<section class="hero"><div class="crumb"><a href="/database/">Database</a> / Features</div><h1>Special Gameplay Features</h1><p class="lead">Verified entry points for Zero Company's distinctive tactical and campaign systems.</p></section><section class="block"><h2>What Makes the Game Distinct</h2><p>Zero Company combines a three-action-point tactical layer with a shared Advantage meter, persistent Injuries and a strategic base called The Den. Missions advance through HoloTable Cycles, while repeated deployments build bonds that unlock squad synergies.</p><p>Character creation is also part of the campaign structure: Hawks and recruited Operators can use eight confirmed species, and most Operators can change standard Specialization through Personnel. These links lead to the strongest current source-grounded guide for each system.</p></section><section class="grid"><a class="card" href="/features/demo-status.html"><strong>Demo Status</strong><br><span class="muted">Current official availability check</span></a><a class="card" href="/official-systems/action-points-official-mechanics.html"><strong>Three-AP Turns</strong></a><a class="card" href="/official-systems/advantage-resource-official-guide.html"><strong>Shared Advantage</strong></a><a class="card" href="/official-systems/wounds-injuries-permadeath.html"><strong>Injuries and Permadeath</strong></a><a class="card" href="/guides/cycles-time-limited-missions.html"><strong>Mission Cycles</strong></a><a class="card" href="/guides/handcrafted-maps-random-enemies.html"><strong>Handcrafted Maps</strong></a><a class="card" href="/guides/bonds-squad-synergy.html"><strong>Squad Bonds</strong></a><a class="card" href="/questions/can-you-create-custom-operators.html"><strong>Custom Operators</strong></a></section><section class="block note"><h2>Pre-release Scope</h2><p>These pages cover systems EA has described publicly. Detailed builds, rewards and balance values remain launch-verification work. The Demo tracker is a dated availability check and will change only when an official page or verified platform store exposes a public build.</p></section><section class="block"><h2>Source Standard</h2><p>Each linked page identifies its first-party evidence and last-check date. Trailer interpretation can help explain a visible system, but exact statistics are excluded until EA publishes them or the released game can be tested directly.</p></section>'''
 write('/features/','Special Gameplay Features','Verified guide entry points for action points, Advantage, permadeath, Mission Cycles, bonds, custom Operators and Demo status.',body,'CollectionPage')

def update_hubs():
 modules={
  'operatives':('/species/','Custom Operator Species','Eight creator species are officially listed.'),
  'builds':('/cosmetics/','Cosmetics and Weapon Themes','Confirmed Deluxe appearance sets and five painted weapon themes.'),
  'official':('/features/demo-status.html','Demo Status','No public Demo is currently listed on EA or Steam.'),
  'media':('/features/demo-status.html','Demo and Media Availability','Track verified public builds and official media.'),
  'start-here':('/database/','Latest Confirmed Data','Release-ready counts for characters, roles, species and systems.'),
  'content-map':('/database/','Game Database','Browse confirmed entities without speculative filler.'),
  'classes':('/species/','Creator Species and Specializations','Eight species and eight standard combat roles.'),
  'planner':('/cosmetics/','Edition Content Database','Compare acquisition conditions before buying.'),
 }
 for tab,(href,title,desc) in modules.items():
  p=ROOT/tab/'index.html'; s=p.read_text(encoding='utf-8-sig',errors='ignore')
  s=re.sub(r'<!-- DATA_UPDATE_START -->.*?<!-- DATA_UPDATE_END -->','',s,flags=re.S)
  block=f'''<!-- DATA_UPDATE_START --><section style="margin:42px 0"><h2>Latest Database Update</h2><a href="{href}" style="display:block;border:1px solid #36e0ce;border-radius:7px;padding:18px;color:inherit;text-decoration:none;background:#0d1922"><small style="color:#9db0bd">CHECKED JUL 19, 2026</small><br><strong style="color:#36e0ce">{escape(title)}</strong><br><span style="color:#9db0bd">{escape(desc)}</span></a></section><!-- DATA_UPDATE_END -->'''
  s=re.sub(r'</main>',block+'</main>',s,count=1,flags=re.I); p.write_text(s,encoding='utf-8')

def add_navigation():
 for p in ROOT.rglob('*.html'):
  s=p.read_text(encoding='utf-8-sig',errors='ignore')
  if 'href="/database/"' not in s and re.search(r'<nav[^>]*>',s,re.I): s=re.sub(r'(<nav[^>]*>)',r'\1<a href="/database/">Database</a>',s,count=1,flags=re.I)
  p.write_text(s,encoding='utf-8')

def main():
 build_species(); build_cosmetics(); build_database(); build_features(); update_hubs(); add_navigation()
 print(f'Built database layer: {len(SPECIES)} species, {len(COSMETICS)} cosmetic entries, gameplay snapshot and Demo status')

if __name__=='__main__': main()
