#!/usr/bin/env python3
"""Generate Round 2 source-grounded entity pages from the June 9 EA overview."""

from html import escape
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = "https://starwarszerocompany.cc"
SOURCE = "https://www.ea.com/games/starwars/zero-company/news/lead-zero-company-to-victory"
CHECKED = "July 18, 2026"

STYLE = """:root{--bg:#071016;--panel:#0d1922;--panel2:#101f2a;--line:#284050;--text:#edf7ff;--muted:#9db0bd;--teal:#36e0ce;--gold:#e9b84a;--red:#ff7468;--max:1080px}*{box-sizing:border-box}body{margin:0;background:radial-gradient(900px 520px at 80% -10%,rgba(54,224,206,.08),transparent),var(--bg);color:var(--text);font:16px/1.68 system-ui,-apple-system,Segoe UI,sans-serif}a{color:var(--teal);text-decoration:none}a:hover{text-decoration:underline}.wrap{max-width:var(--max);margin:auto;padding:0 22px}.top{border-bottom:1px solid var(--line);background:rgba(7,16,22,.95);position:sticky;top:0;z-index:5}.top .wrap{min-height:62px;display:flex;align-items:center;gap:16px;flex-wrap:wrap}.brand{font-weight:900;color:var(--text)}.nav{margin-left:auto;display:flex;gap:14px;flex-wrap:wrap}.nav a{color:var(--muted);font-size:14px}.hero{padding:52px 0 30px;border-bottom:1px solid var(--line)}.crumb{font-size:12px;text-transform:uppercase;letter-spacing:.15em;color:var(--teal)}h1{font-size:clamp(34px,6vw,58px);line-height:1.05;margin:14px 0}h2{font-size:23px;margin:34px 0 13px;border-left:4px solid var(--teal);padding-left:12px}h3{margin:0 0 8px}.lead{font-size:19px;color:#c4d4dd;max-width:820px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(235px,1fr));gap:15px}.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card,.block{border:1px solid var(--line);border-radius:8px;background:linear-gradient(180deg,var(--panel),var(--panel2));padding:20px;margin:15px 0}.card{display:block;color:var(--text)}.pill{display:inline-block;border:1px solid var(--line);border-radius:4px;padding:5px 9px;margin:5px 7px 0 0;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em}.gold{color:var(--gold);border-color:rgba(233,184,74,.45)}.teal{color:var(--teal);border-color:rgba(54,224,206,.45)}.unknown{border-color:rgba(233,184,74,.4)}.mini,.source{color:var(--muted);font-size:14px}.source{border-top:1px solid var(--line);padding-top:14px}li{margin:8px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid var(--line);padding:11px;text-align:left;vertical-align:top}th{color:var(--gold)}footer{border-top:1px solid var(--line);margin-top:48px;padding:28px 0;color:var(--muted);font-size:14px}@media(max-width:760px){.two{grid-template-columns:1fr}.nav{margin-left:0}.top .wrap{padding-top:12px;padding-bottom:12px}}"""


def page(route, title, description, crumb, h1, lead, body, related):
    canonical = SITE + route
    schema = {
        "@context": "https://schema.org", "@type": "Article", "headline": title,
        "description": description, "url": canonical, "dateModified": "2026-07-18",
        "about": "Star Wars Zero Company",
        "isPartOf": {"@type": "WebSite", "name": "Star Wars Zero Company Wiki", "url": SITE + "/"}
    }
    cards = "".join(f'<a class="card" href="{url}"><strong>{escape(name)}</strong><br><span class="mini">{escape(note)}</span></a>' for url, name, note in related)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(description, quote=True)}"><meta name="robots" content="index,follow"><link rel="canonical" href="{canonical}"><link rel="icon" href="/favicon.ico"><meta property="og:type" content="article"><meta property="og:url" content="{canonical}"><meta property="og:title" content="{escape(title, quote=True)}"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:site_name" content="Star Wars Zero Company Wiki"><script type="application/ld+json">{json.dumps(schema, ensure_ascii=False)}</script><style>{STYLE}</style></head><body><header class="top"><div class="wrap"><a class="brand" href="/">Star Wars Zero Company Wiki</a><nav class="nav"><a href="/operatives/">Operatives</a><a href="/facilities/">The Den</a><a href="/lore/">Story &amp; Lore</a><a href="/official-systems/">Systems</a><a href="/official/">Official Info</a></nav></div></header><main class="wrap"><section class="hero"><div class="crumb">{escape(crumb)}</div><h1>{escape(h1)}</h1><p class="lead">{lead}</p><span class="pill teal">Officially confirmed</span><span class="pill gold">Checked {CHECKED}</span></section>{body}<section><h2>Related Guides</h2><div class="grid">{cards}</div></section><section class="block"><h2>Source and Verification</h2><p>This page uses EA's official June 9, 2026 gameplay overview. The game remains in development, so exact costs, balance values and final behavior should be checked again against the launch build.</p><p class="source"><a href="{SOURCE}" rel="nofollow">EA: Lead Zero Company To Victory on August 27</a> · Last fact-check: {CHECKED}</p></section></main><footer><div class="wrap">Unofficial Star Wars Zero Company player guide. <a href="/about/sources-and-citations.html">Sources policy</a> · <a href="/sitemap.xml">Sitemap</a></div></footer></body></html>'''


OPERATIVES = {
    "hawks": ("Hawks", "Former Grand Army of the Republic captain and leader of Zero Company.", "Human or customizable protagonist", "Zero Company leader", "Former Republic captain", "EA describes Hawks as clever, cool-headed and decisive. Hawks accepts operators from any background if they can complete the job.", "Hawks is the player-led commander of Zero Company. His appearance and species can be customized, but final combat abilities, starting weapon and optimal specialization are not yet confirmed by the official overview."),
    "trick": ("Trick (CT-3301)", "Clone Trooper, veteran soldier and long-time ally of Hawks.", "Clone", "Authored Operator", "Formerly CT-3301", "Trick served with Hawks in the Republic military and is described as a consummate soldier who enjoys games of chance.", "The official overview confirms Trick's identity and background but does not publish his full skill tree, weapon statistics or launch-build ranking."),
    "telrea": ("Tel-Rea Vokoss", "Tognath Jedi Padawan driven to honor the legacy of her late Jedi Master.", "Tognath", "Authored Operator", "Jedi Padawan", "Tel-Rea joins Zero Company with discipline and determination. EA also uses her Force Push as an example of knocking an enemy out of cover and into Overwatch.", "Force Push is confirmed as an ability example. Its exact AP cost, damage, upgrades and cooldown are not yet stated in the official article."),
    "cly": ("Cly Kullervo", "Mandalorian warrior and one of the last surviving members of Clan Verminoth.", "Mandalorian", "Authored Operator", "Clan Verminoth", "Cly joins Zero Company to advance an implacable quest for revenge. EA calls Clan Verminoth ancient and says Cly is one of its last survivors.", "The official overview confirms her story identity but not a complete ability list, preferred weapon, build or comparative tier."),
    "luco": ("Luco Bronc", "Sharp-tongued Umbaran sniper who defended Umbara during the Republic invasion.", "Umbaran", "Authored Operator", "Sniper", "Luco has no love for the Republic that defeated and occupied his world, but he sets those differences aside to work with Zero Company.", "His sniper identity is confirmed. Exact weapon stats, range bonuses and skill-tree choices should remain unranked until official or launch-build data is available."),
    "jae": ("Jae Mordant", "Former Ore-Baroness of Luunata and a key figure in hiring Zero Company.", "From House Mordant of Shu-Torun", "Authored Operator", "Former Ore-Baroness", "After leaving ruthless House Mordant, Jae built a mining citadel on Luunata. Kundri Fathom and the Infinite Coil seized the planet for the Separatists, and Jae wants it back.", "EA confirms Jae's story role and motivation, but does not yet publish a full combat role, ability tree or optimal loadout."),
    "kabb": ("Kabbney “Kabb” Uppercut", "Felshi former prizefighter, veteran crook and Zero Company operator.", "Felshi", "Authored Operator", "Cybernetic-arm brawler", "Kabb is known for his cybernetic arm, knockout punch and rhyming dialect. The Felshi are an original species created specifically for Zero Company.", "EA confirms Kabb's Uppercut can knock enemies out of cover into Overwatch. Exact AP cost, damage and upgrade effects remain unconfirmed."),
}


def operative_page(slug, data):
    name, lead, species, operator_type, identity, confirmed, unknown = data
    desc = f"Officially verified {name} guide for Star Wars Zero Company: identity, background, known combat clues and what remains unconfirmed before launch."
    body = f'''<section class="two"><div class="block"><h2>Quick Profile</h2><table><tr><th>Field</th><th>Confirmed information</th></tr><tr><td>Species / origin</td><td>{escape(species)}</td></tr><tr><td>Type</td><td>{escape(operator_type)}</td></tr><tr><td>Identity</td><td>{escape(identity)}</td></tr></table></div><div class="block"><h2>Who Is {escape(name)}?</h2><p>{escape(confirmed)}</p></div></section><section class="block"><h2>Confirmed Gameplay Information</h2><p>{escape(confirmed)}</p><p>Authored Operators join as the story unfolds. In the Personnel facility, most Operators can change Specialization, develop Bonds and spend Focus Points on Talents, Abilities and Passives. This does not mean every specialization or build is equally suitable; final recommendations require launch testing.</p></section><section class="block unknown"><h2>What Is Not Confirmed Yet?</h2><p>{escape(unknown)}</p><ul><li>No pre-launch tier rating is treated as final.</li><li>No invented Focus Tree nodes or percentages are presented as official facts.</li><li>Build advice will be added only after abilities and equipment are verified.</li></ul></section>'''
    return page(f"/operatives/{slug}.html", f"{name} Guide: Confirmed Profile & Role | Star Wars Zero Company", desc, "Operative dossier", name, escape(lead), body, [("/operatives/", "All Operatives", "Verified authored Operator profiles"), ("/official-systems/focus-trees-cross-training.html", "Focus Trees", "How progression and Specialization changes work"), ("/official-systems/squad-bonds-training.html", "Squad Bonds", "Confirmed relationship and Cross Training mechanics")])


FACILITIES = {
 "holotable": ("HoloTable", "The HoloTable is the mission-planning center for Tactical Missions, Operations and Zone Influence.", "At the HoloTable, players view the available Operations and Tactical Missions for the current Cycle and track Zero Company's Influence.", ["Operations are non-combat assignments that can gather information, loot or Credits.", "Operations cost Intel; Intel is earned through Tactical Missions.", "Tactical Missions advance the game to the next Cycle after completion.", "Some activities expire, so the HoloTable supports time-sensitive planning."], "Exact mission pools, Cycle length and every reward table remain launch-verification items."),
 "recruitment": ("Recruitment Facility", "Recruit Custom Operators with Credits or prepare your own candidate pool.", "Each Cycle offers a selection of Custom Operators. Their name, Talent, Primary Specialization, weapon type and backstory can be adjusted after recruitment.", ["The candidate selection can be refreshed at will.", "Players can create their own pool of Custom Operators.", "Recruitment is limited by Roster Capacity.", "The game can present varied recruits while still allowing direct customization."], "Recruit costs, refresh behavior and Roster Capacity upgrades are not yet numerically confirmed."),
 "personnel": ("Personnel Facility", "Manage stats, Focus Trees, Specializations and Bonds between Operators.", "The Personnel facility displays combat stats, Soldier Bonds and Focus Trees. It is the central progression screen for individual Operators and pair relationships.", ["Focus Points improve Talents, Abilities and Passives.", "Most Operators can change Specialization from this facility.", "Bond levels can grant permanent Cross Training combat bonuses.", "Maximum Bonds unlock a special Passive-based Cross Training benefit."], "Exact Focus Point costs, Bond thresholds and stat bonuses await launch-build verification."),
 "armory": ("Armory", "Equip weapons, Weapon Modifications and combat Utilities at the Den.", "The Armory manages default weapons, weapon swaps, modification slots, Utilities and the Black Market inventory.", ["Four weapon types are confirmed: Longarm, Repeater, Rifle and Pistol.", "Weapon Modifications alter stats and can apply distinct effects.", "Modification Slot counts can grow during the campaign.", "Utilities include items such as Impact Bombs and Concussion Grenades."], "Complete item lists, prices, stat ranges and best-in-slot claims are not confirmed pre-launch."),
 "upgrade": ("Upgrade Facility", "Build Den infrastructure and roster-wide improvements over campaign Cycles.", "The Upgrade facility funds improvements to the Den and Zero Company, including infrastructure unlocks and company-wide combat upgrades.", ["A Droid Bay upgrade enables Astromech Custom Operator recruitment.", "Roster-wide weapon upgrades can enhance all Operators.", "Construction takes at least one Cycle.", "Available Build Slots limit simultaneous construction; more slots unlock over time."], "The full upgrade tree, costs, prerequisites and optimal sequence are not yet official."),
 "medbay": ("Medbay", "Treat injured Operators with standard beds or immediate Bacta Tank recovery.", "The Medbay is the Den facility for removing Injuries earned during Operations and Tactical Missions.", ["A standard bed takes one Cycle to heal an Operator.", "The Bacta Tank provides instant recovery.", "Healing costs Credits.", "Recovery choices interact with roster depth and time-sensitive missions."], "Exact Credit costs, Bacta availability and capacity upgrades require launch verification."),
 "customization": ("Customization Facility", "Change Operator appearance, outfits and supported species at the Den.", "The Customization facility can update cosmetic appearance at any time. Hawks and Custom Operators also have supported species choices.", ["Hawks options named by EA: Devaronian, Human, Mirialan, Togruta, Twi’lek and Zabrak.", "Custom Operator options also include Neimoidian, Ovissian, Rodian and Weequay.", "Voices, outfits and other appearance elements can be customized.", "Authored Operator customization is more limited than Hawks and Custom Operators."], "The complete cosmetic catalog, unlock sources and edition restrictions are not fully listed."),
 "memorial": ("Memorial", "Review fallen Operators and the service records they left behind.", "The Memorial records Operators who permanently die during the campaign and lets players revisit their legacy.", ["It displays statistics and accomplishments from a fallen Operator's service.", "Permanent death occurs after three Injuries on standard difficulty.", "The Memorial reinforces campaign continuity rather than erasing a loss.", "No member of Zero Company is guaranteed protection from permanent death."], "The final list of tracked statistics and any gameplay effects of the Memorial remain unknown."),
 "command-center": ("The Den Command Center", "The Den is Zero Company's base on the Ring of Kafrene and the hub connecting every campaign system.", "Between missions, the camera moves to third person inside the Den. Players prepare the company, talk with authored Operators and use specialized facilities.", ["Plot missions and Operations at the HoloTable.", "Recruit and manage Operators.", "Treat Injuries, change equipment and construct upgrades.", "Talk with squad members to learn their views on unfolding events."], "The final Den layout, unlock sequence and all interaction points require launch exploration."),
}


def facility_page(slug, data):
    name, lead, overview, facts, unknown = data
    body = f'''<section class="block"><h2>What Does the {escape(name)} Do?</h2><p>{escape(overview)}</p></section><section class="two"><div class="block"><h2>Confirmed Functions</h2><ul>{''.join(f'<li>{escape(x)}</li>' for x in facts)}</ul></div><div class="block unknown"><h2>Launch Verification Boundary</h2><p>{escape(unknown)}</p><p>This page deliberately avoids invented costs, rankings and upgrade orders.</p></div></section><section class="block"><h2>Why This Facility Matters</h2><p>The Den connects tactical combat with long-term campaign decisions. Using the {escape(name)} changes what Zero Company can attempt next, how prepared the roster is and which resources remain available. The practical guide will expand after the shipped economy and interface can be tested.</p></section>'''
    return page(f"/facilities/{slug}.html", f"{name} Guide | Star Wars Zero Company Den Facilities", f"Official {name} guide for Star Wars Zero Company: confirmed functions, campaign role and launch details still awaiting verification.", "The Den facility", name, escape(lead), body, [("/facilities/", "All Den Facilities", "Complete verified facility directory"), ("/official-systems/the-den-facilities-guide.html", "The Den Overview", "How the base-management layer fits together"), ("/official-systems/mission-types-official-framework.html", "Mission Types", "Operations, Tactical Missions and Cycles")])


LORE = {
 "kundri-fathom": ("Kundri Fathom", "Kundri Fathom is the main named antagonist currently revealed for Star Wars Zero Company.", "EA calls Fathom the enigmatic leader of the Infinite Coil, a Separatist-aligned cult. Zero Company must track down and stop Fathom before the cult's actions push the galaxy beyond the brink.", ["Leads the Infinite Coil.", "Aligned with the Separatist cause.", "Seized Luunata with the cult for the Separatists.", "The Den's Upgrade description frames stopping Fathom as the campaign's strategic objective."], "Fathom's species, detailed history, combat role and final fate have not been revealed."),
 "infinite-coil": ("The Infinite Coil", "The Infinite Coil is a Separatist-aligned cult and Zero Company's central enemy organization.", "The official overview describes a shadow war beneath the wider Clone Wars. The Infinite Coil operates within that conflict under Kundri Fathom and has already taken Luunata.", ["Led by Kundri Fathom.", "Separatist-aligned rather than identified as a standard droid army unit.", "Responsible for taking Jae Mordant's mining world, Luunata.", "Its threat drives Zero Company's recruitment, upgrades and campaign Operations."], "The cult's hierarchy, units, beliefs and complete list of controlled worlds are not yet public."),
 "zero-company": ("Zero Company", "Zero Company is an unconventional outfit of skilled Operators for hire led by Hawks.", "The company recruits Authored and Custom Operators from varied backgrounds. It operates from the Den on the Ring of Kafrene and is hired to stop Kundri Fathom and the Infinite Coil.", ["Led by former Republic captain Hawks.", "Includes a Clone Trooper, Jedi Padawan, Mandalorian, Umbaran sniper and other authored characters.", "Can recruit fully customizable Operators.", "Relationships, injuries and permanent losses shape the company across the campaign."], "The full roster size, every recruitable species and the final campaign outcome remain unconfirmed."),
 "ring-of-kafrene": ("Ring of Kafrene", "The Ring of Kafrene is the location of the Den, Zero Company's home base.", "EA places the Den inside a hulking hangar on the Ring of Kafrene. From this base, Zero Company plans incursions, recruits Operators, treats Injuries and prepares for the Infinite Coil.", ["Hosts the Den and its Command Center facilities.", "Functions as the between-mission campaign hub.", "Uses a third-person camera inside the base.", "Connects the HoloTable, Personnel, Armory, Medbay and other facilities."], "The explorable boundaries, map layout and additional Kafrene story events are not yet described."),
}


def lore_page(slug, data):
    name, lead, overview, facts, unknown = data
    body = f'''<section class="block"><h2>Quick Answer</h2><p>{escape(overview)}</p></section><section class="two"><div class="block"><h2>Confirmed Facts</h2><ul>{''.join(f'<li>{escape(x)}</li>' for x in facts)}</ul></div><div class="block unknown"><h2>Not Yet Revealed</h2><p>{escape(unknown)}</p></div></section><section class="block"><h2>Role in the Campaign</h2><p>{escape(overview)} This page stays spoiler-aware and will separate pre-release facts from discoveries made in the final game.</p></section>'''
    return page(f"/lore/{slug}.html", f"{name} Explained | Star Wars Zero Company Story Guide", f"Who or what is {name} in Star Wars Zero Company? Confirmed story role, relationships and facts from EA's official gameplay overview.", "Story & lore", name, escape(lead), body, [("/lore/", "Story & Lore Hub", "Confirmed factions, people and places"), ("/operatives/", "Zero Company Operatives", "Verified squad dossiers"), ("/confirmed/confirmed-gameplay-loop.html", "Confirmed Gameplay Loop", "Source-grounded campaign overview")])


def hub(route, name, lead, items, crumb):
    cards = "".join(f'<a class="card" href="{route}{slug}.html"><strong>{escape(data[0])}</strong><br><span class="mini">{escape(data[1])}</span></a>' for slug, data in items.items())
    body = f'<section><h2>Verified Directory</h2><div class="grid">{cards}</div></section><section class="block"><h2>Editorial Rule</h2><p>Every page in this directory separates confirmed information from launch-build unknowns. Pages are expanded when official sources or first-hand testing provide concrete evidence.</p></section>'
    return page(route, f"{name} | Star Wars Zero Company Wiki", lead, crumb, name, escape(lead), body, [("/official-systems/", "Official Systems", "Verified gameplay mechanics"), ("/official/", "Official Information", "Release, platform and edition facts"), ("/about/sources-and-citations.html", "Sources Policy", "How facts and unknowns are labeled")])


def write(relative, content):
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main():
    for slug, data in OPERATIVES.items():
        write(f"operatives/{slug}.html", operative_page(slug, data))
    for slug, data in FACILITIES.items():
        write(f"facilities/{slug}.html", facility_page(slug, data))
    for slug, data in LORE.items():
        write(f"lore/{slug}.html", lore_page(slug, data))
    write("facilities/index.html", hub("/facilities/", "The Den Facilities", "Verified guides to the HoloTable, Recruitment, Personnel, Armory, Upgrade, Medbay, Customization and Memorial facilities.", FACILITIES, "The Den"))
    write("lore/index.html", hub("/lore/", "Star Wars Zero Company Story & Lore", "Spoiler-aware profiles for Zero Company, Kundri Fathom, the Infinite Coil and the Ring of Kafrene.", LORE, "Story & lore"))
    print(f"Generated {len(OPERATIVES)} upgraded Operatives and {len(FACILITIES) + len(LORE) + 2} new entity pages")


if __name__ == "__main__":
    main()
