#!/usr/bin/env python3
"""Round 3: replace speculative class pages with verified Specialization guides."""

from html import escape
from round2_generate import page, write, SOURCE, CHECKED

STANDARD = {
    "assault": ("Assault", "Frontline fighter", "Medium to close range", "Maneuvers aggressively to defeat targets hiding in cover.", ["Use movement to create a better firing angle instead of trading into strong cover.", "Reserve enough AP to finish in a defensible position when a flank does not guarantee a kill.", "Works best when the squad can reveal targets or reduce the risk of moving forward."], "EA has not published the Assault's named Ultimate, Standard Ability, Passive, starting weapon or final damage values."),
    "gunslinger": ("Gunslinger", "Multi-target attacker", "Flexible blaster range", "Uses multi-target blaster attacks and fast strikes to spread offense across several targets.", ["Look for turns where damage can be distributed without leaving dangerous enemies barely alive.", "Coordinate with allies that soften several targets or expose multiple firing opportunities.", "Do not assume kill-refresh or free-shot mechanics until the actual Ability text is verified."], "No official named Ability, AP refund, weapon lock or launch-build tier has been published."),
    "heavy": ("Heavy", "Durable frontline combatant", "Frontline / exposed positions", "Uses armor and survivability to absorb pressure while fighting in the open.", ["Use the Heavy to occupy dangerous space, not as proof that cover can always be ignored.", "Protect fragile Operators by drawing or surviving pressure that would disrupt the backline.", "Pair durability with mission progress; surviving without advancing an objective can still lose tempo."], "The exact armor rules, damage reduction, taunt access and weapon type remain unconfirmed."),
    "medic": ("Medic", "Healing and Injury prevention", "Squad support", "Heals Operators, helps prevent Injuries and can boost teammates physically and psychologically.", ["Prioritize preventing a Downed state when the third Injury could cause permanent death.", "Balance immediate healing against spending AP on movement, attacks or mission objectives.", "A deep roster still matters because Medbay recovery and mission timing continue between battles."], "EA has awaiting launch verification named healing skills, buff percentages, passive Injury odds or equipment restrictions."),
    "scoundrel": ("Scoundrel", "Opportunistic wildcard", "Situation dependent", "Takes advantage of messy situations with little preparation and makes the most of combat opportunities.", ["Treat the Scoundrel as an adaptable role rather than assuming one fixed damage rotation.", "Use information from the current battlefield before committing scarce AP.", "Pairing and build rankings should wait until the actual Talent and Ability trees can be tested."], "Specific crit guarantees, gamble mechanics, weapon bindings and final power ranking are not official."),
    "scout": ("Scout", "Reconnaissance and setup", "Team-wide tactical support", "Uses planning and timing to create opportunities for the whole squad.", ["Gather or exploit information before high-cost attacks are committed.", "Plan around mission objectives and enemy movement, not only personal damage.", "Use Scout-created openings with finishers that can convert information into progress."], "Map-wide reveal, detection bonuses, exact Overwatch interactions and weapon choices are not yet confirmed."),
    "sharpshooter": ("Sharpshooter", "Long-range marksman", "Long range", "Singles out chosen enemies and excels in long-range engagements.", ["Choose priority targets whose removal changes the enemy turn.", "Protect sightlines and distance rather than assuming every map provides safe high ground.", "Use cover removal, forced movement or team setup to improve difficult shots."], "No guaranteed-shot Ultimate, elevation percentage, weapon lock or best-target table has been officially published."),
    "soldier": ("Soldier", "Mainstay offensive unit", "Close to medium range", "Fights with melee, grenades, heavy blaster fire and a powerful rocket launcher.", ["Choose the tool that fits the target and objective instead of treating Soldier as a single-range role.", "Grenades and rockets may solve cover or group problems, but final costs and limits need verification.", "The broad kit suggests flexibility; it does not prove a launch tier or optimal build."], "Exact grenade inventory, rocket Ability, melee values, weapon restrictions and cooldowns remain unknown."),
}

NONSTANDARD = {
    "astromech": ("Astromech Operators", "Astromechs are confirmed Custom Operator recruits unlocked through a Droid Bay upgrade.", "EA confirms Astromech recruitment through the Upgrade system, but does not list Astromech among the eight standard Specializations. Treat Astromech as an Operator type until the final class structure is verified."),
    "jedi": ("Jedi Padawan Archetype", "Tel-Rea Vokoss is a confirmed Tognath Jedi Padawan and authored Operator.", "Force Push is confirmed as an example that can knock enemies out of cover into Overwatch. EA does not identify Jedi Padawan as one of the eight standard Specializations or publish a complete Jedi skill tree."),
    "mando": ("Mandalorian Archetype", "Cly Kullervo is a confirmed Mandalorian and member of ancient Clan Verminoth.", "Cly's story identity is official, but EA does not list Mandalorian Warrior among the eight standard Specializations. Jetpack skills, weapon bindings and mobility rankings are awaiting launch verification."),
    "secret": ("Unrevealed Specialization Status", "EA currently identifies eight standard Specializations and says most Operators use one of them.", "That wording may leave room for authored or special archetypes, but it does not confirm a named secret class. This URL stays out of the sitemap until an official source or the launch build identifies a distinct Specialization."),
}


def standard_page(slug, data):
    name, role, range_label, official, play, unknown = data
    body = f'''<section class="two"><div class="block"><h2>Official Role</h2><table><tr><th>Field</th><th>Confirmed</th></tr><tr><td>Specialization</td><td>{escape(name)}</td></tr><tr><td>Role</td><td>{escape(role)}</td></tr><tr><td>Engagement</td><td>{escape(range_label)}</td></tr><tr><td>Ability structure</td><td>One Ultimate, one Standard Ability and one Passive</td></tr></table></div><div class="block"><h2>Quick Answer</h2><p>{escape(official)}</p></div></section><section class="block"><h2>How to Think About {escape(name)}</h2><ul>{''.join(f'<li>{escape(x)}</li>' for x in play)}</ul><p>These are decision principles derived from the officially stated role. They are not a final build, tier ranking or substitute for launch testing.</p></section><section class="block unknown"><h2>Awaiting Launch Verification</h2><p>{escape(unknown)}</p><p>The page will add named Abilities, Focus Tree choices, AP costs, compatible weapons and tested squad pairings only after they can be supported by the shipped game or a later official breakdown.</p></section><section class="block"><h2>Specialization and Progression</h2><p>EA says most Operators use one of eight standard Specializations. Each standard Specialization contains an Ultimate, a Standard Ability and a Passive unique to that Specialization. In the Personnel facility, most Operators can change Specialization, and Focus Points can improve Talents, Abilities and Passives.</p></section>'''
    return page(f"/classes/{slug}.html", f"{name} Specialization Guide | Star Wars Zero Company", f"Verified {name} Specialization guide for Star Wars Zero Company: official role, tactical use, progression structure and launch details still awaiting launch verification.", "Standard Specialization", f"{name} Specialization", escape(official), body, [("/classes/", "All Standard Specializations", "Compare the eight official roles"), ("/official-systems/action-points-official-mechanics.html", "Action Points", "How movement, attacks and Abilities compete for AP"), ("/official-systems/focus-trees-cross-training.html", "Focus Trees", "Progression and Specialization changes")])


def nonstandard_page(slug, data):
    name, lead, boundary = data
    body = f'''<section class="block"><h2>Current Official Status</h2><p>{escape(boundary)}</p></section><section class="block unknown"><h2>Why This Page Is Not in the Sitemap</h2><p>This concept is connected to confirmed characters or systems, but it is not currently supported as one of the eight named standard Specializations. The page remains crawlable for internal navigation while carrying <code>noindex,follow</code>.</p></section><section class="block"><h2>What Would Change the Status?</h2><ul><li>An EA article naming it as a Specialization.</li><li>A launch-build screen showing its Ultimate, Standard Ability and Passive.</li><li>First-hand verification of how it differs from Operator identity, species or equipment.</li></ul></section>'''
    html = page(f"/classes/{slug}.html", f"{name} | Star Wars Zero Company Class Status", f"Current official status of {name} in Star Wars Zero Company and why it is not treated as a confirmed standard Specialization.", "Class status", name, escape(lead), body, [("/classes/", "Standard Specializations", "The eight roles named by EA"), ("/operatives/", "Authored Operators", "Verified character identities"), ("/about/sources-and-citations.html", "Sources Policy", "How uncertain claims are handled")])
    return html.replace('<meta name="robots" content="index,follow">', '<meta name="robots" content="noindex,follow">')


def hub_page():
    cards = ''.join(f'<a class="card" href="/classes/{slug}.html"><strong>{escape(data[0])}</strong><br><span class="mini">{escape(data[1])}: {escape(data[3])}</span></a>' for slug, data in STANDARD.items())
    body = f'''<section class="block"><h2>Quick Answer</h2><p>EA has confirmed eight standard Specializations: Assault, Gunslinger, Heavy, Medic, Scoundrel, Scout, Sharpshooter and Soldier. Most Operators use one of these roles, and most can change Specialization through the Personnel facility.</p></section><section><h2>Eight Standard Specializations</h2><div class="grid">{cards}</div></section><section class="block"><h2>Why There Is No Pre-launch Tier List</h2><p>A trustworthy tier list requires final Ability text, AP costs, enemy design, mission objectives, difficulty settings and launch balance. Those inputs are not fully public. This hub therefore compares official roles without assigning S, A or B rankings.</p></section><section class="two"><div class="block"><h2>Shared Structure</h2><p>Every standard Specialization has three unique Ability components: an Ultimate, a Standard Ability and a Passive.</p></div><div class="block"><h2>Progression</h2><p>Focus Points can improve Talents, Abilities and Passives. Bonds and Cross Training can also add permanent combat bonuses to Operator pairs.</p></div></section>'''
    return page("/classes/", "Star Wars Zero Company Specializations: All 8 Official Classes", "All eight official Star Wars Zero Company Specializations explained by role, range and tactical purpose, without speculative pre-launch tier rankings.", "Class guide hub", "All 8 Standard Specializations", "Compare the eight roles officially named by EA and see what remains unknown before launch.", body, [("/operatives/", "Operatives", "Characters who can use and change roles"), ("/facilities/personnel.html", "Personnel Facility", "Where Specializations and Focus Trees are managed"), ("/official-systems/gameplay-overview-breakdown.html", "Gameplay Overview", "Official combat and campaign systems")])


def main():
    for slug, data in STANDARD.items():
        write(f"classes/{slug}.html", standard_page(slug, data))
    for slug, data in NONSTANDARD.items():
        write(f"classes/{slug}.html", nonstandard_page(slug, data))
    write("classes/index.html", hub_page())
    print("Generated 8 verified standard Specializations, 4 noindex boundary pages and a new class hub")


if __name__ == "__main__":
    main()
